### ISSUE TITLE
Add sample names to reconstruction output

### ISSUE THREAD

**Issue by hantan1234** [Tripati-Lab/BayClump#23]
Is there a way to have the file export the sample names in a 5th column alongside the D47s for the reconstructions? Otherwise its a simple matter of copying and pasting from the input file, but could save that extra step if you have time!

**Comment by cromanpa94** [comment]
Ordering of the reconstructed temperatures fixed in https://github.com/Tripati-Lab/BayClump/commit/0f46df9ec4e975243e80d5bf3e80ec647207a619. 

For Bayesian models, pass extra column:

https://github.com/Tripati-Lab/BayClump/blob/dev/server.R#L1380
https://github.com/Tripati-Lab/BayClump/blob/dev/server.R#L1357
https://github.com/Tripati-Lab/BayClump/blob/dev/server.R#L1334

**Comment by cromanpa94** [comment]
Function added in https://github.com/Tripati-Lab/BayClump/commit/8febc676934d9713d8b8072613a5cda70ac451b0
